name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure requirements.txt exists at the root

      - name: Run tests
        run: |
          # Replace with your actual test command, for example:
          # If using pytest: pytest
          # If using unittest: python -m unittest discover
          echo "Run your tests here"  # Replace with actual test command

      - name: Deploy to AWS S3 bucket
        run: |
          aws s3 cp . s3://tushar-static-site-bucket-2025/ --recursive
